Athena/urls.py
from django.urls import path
from Athena import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.Dash.as_view(), name='home_page'),
    path('dash', views.Dash.as_view(), name='dash_page'),
    path('course', views.Courses.as_view(), name='course_page'),
    path('login', views.Login.as_view(), name='login_page'),
    path('course/<int:course_id>', views.CourseDetails.as_view(), name='course_details_page'),
    path('course/enrollment', views.EnrollCourse.as_view(), name='course_enrollment'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AthenaProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Athena.urls')),
]

Athena/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator


# Define custom path form files for each user
def user_directory_path(instance, filename):
    return f'user_{instance.user.username}/{filename}'


class Membership(models.Model):
    CHOICES = [
        ('Greater', 'Greater'),
        ('Inter', 'Inter'),
        ('Lesser', 'Lesser'),
        ('Demi', 'Demi')
    ]
    type = models.CharField(choices=CHOICES, max_length=10, default='D', blank=False, null=False, unique=True)
    price = models.PositiveIntegerField()

    def __str__(self):
        return self.type


# Create your models here.
class User(AbstractUser):
    email = models.EmailField(unique=True)
    membership = models.ForeignKey(Membership, on_delete=models.CASCADE, default=1)


class Course(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    course_title = models.CharField(max_length=255, blank=False, null=False)
    course_desc = models.TextField(max_length=1024, blank=False, null=False)
    course_start_date = models.DateField()
    course_end_date = models.DateField()
    course_day = models.CharField(max_length=14, blank=True, null=True)
    course_created = models.DateField()
    course_rating = models.DecimalField(max_digits=2, decimal_places=1, default=0, validators=[MinValueValidator(0.0),
                                                                                               MaxValueValidator(5.0)])
    last_update = models.DateField(auto_now=True)
    categories = models.CharField(max_length=512, blank=False, null=False, default='')

    TYPE_CHOICES = [
        ('V', 'Virtual'),
        ('I', 'In-Person')
    ]

    course_type = models.CharField(max_length=1, choices=TYPE_CHOICES, default='I', null=True)

    DIF_CHOICES = [
        ('A', 'Advanced'),
        ('I', 'Intermediate'),
        ('B', 'Beginner')
    ]

    course_difficulty = models.CharField(max_length=1, choices=DIF_CHOICES, default='B', null=False)

    # course_banner = models.ImageField(upload_to=user_directory_path_course)

    def __str__(self):
        return self.course_title + '_' + str(self.author.username)


class Enrollment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user.username + '_' + str(self.course.id)

    class Meta:
        unique_together = ['user', 'course']


class UserProfiles(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    img = models.ImageField(upload_to=user_directory_path)

    def __str__(self):
        return self.user.username

Athena/forms.py
from django import forms
from .models import *


class EnrollmentForm(forms.ModelForm):
    class Meta:
        model = Enrollment
        fields = '__all__'

Athena/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django import views
from django.contrib.auth import get_user_model, authenticate, login, logout

from .forms import *
from .models import *
from django.http import JsonResponse


# def load_profile(context, request):
#     user = request.user
#     if user.is_authenticated:
#         try:
#             old_profile = UserProfiles.objects.get(user=user)
#             context['profile_img'] = old_profile.img
#         except UserProfiles.DoesNotExist:
#             print('No User profile_img present')
#         return context
#     return context
#

# Create your views here.
class Dash(views.View):

    def get(self, request):
        context = {'title': 'Dashboard'}
        # load_profile(context, request)
        return render(request, 'Athena/dash_page.html', context)


class Courses(views.View):

    def get(self, request):
        context = {'title': 'Courses'}
        # load_profile(context, request)

        # trending_courses = Course.objects.order_by('-course_rating')[:5]
        # context['t_courses'] = trending_courses
        # # print(trending_courses)
        # # [print(x.course_title, x.course_rating) for x in trending_courses]
        # my_courses = Course.objects.filter(author=request.user)
        # context['my_courses'] = my_courses
        #
        # enrolled_courses = Enrollment.objects.filter(user=request.user)
        # context['e_courses'] = enrolled_courses
        #
        # view_courses = Course.objects.order_by('-course_rating')[:9]
        # context['v_courses'] = view_courses

        return render(request, 'Athena/course_page.html', context)


class Login(views.View):

    def get(self, request):
        context = {'title': 'Login'}
        return render(request, 'Athena/login.html', context)

    def post(self, request):
        email = request.POST['email']
        password = request.POST['password']
        print("Login :", email, password)
        User = get_user_model()
        try:
            user_e = User.objects.get(email__exact=email)
        except User.DoesNotExist as e:
            print('New user, redirect to signin page')
            return redirect('signup_page')
        else:
            print(user_e.username)
            user = authenticate(request, username=user_e.username, password=password)
            if user is not None:
                login(request, user)
                print('Opening dashboard for the user {}'.format(user_e.username))
                return redirect('dash_page')
            else:
                print('Login password combination incorrect')
                return redirect('login_page')


class CourseDetails(views.View):

    def get(self, request, course_id):
        context = {'title': 'Course Details'}
        load_profile(context, request)
        course = Course.objects.get(id=course_id)

        if course.author == request.user:
            return redirect(reverse('course_author_page', args=[course_id]))

        author_profile = UserProfiles.objects.get(user=course.author)
        context['course'] = course
        context['author_profile'] = author_profile.img

        # Current User course details
        try:
            e_obj = Enrollment.objects.get(user=request.user, course=course)
        except Enrollment.DoesNotExist:
            e_obj = None
        context['e_obj'] = e_obj

        # All enrollment details
        enrollment_info = Enrollment.objects.filter(course=course)
        context['e_info'] = enrollment_info

        e_data = {
            'user': request.user,
            'course': course
        }
        e_form = EnrollmentForm(initial=e_data)

        e_form.fields['user'].widget.attrs['style'] = 'display: none;'
        e_form.fields['course'].widget.attrs['style'] = 'display: none;'

        context['e_form'] = e_form

        return render(request, 'Athena/course_details_page.html', context)


class EnrollCourse(views.View):

    def post(self, request):
        context = {}
        e_form = EnrollmentForm(request.POST)
        if e_form.is_valid():
            e_form.save()
            return redirect(reverse('course_details_page', args=[e_form.cleaned_data['course'].id]))
        else:
            return redirect('course_page')


def load_profile(context, request):
    user = request.user
    if user.is_authenticated:
        try:
            old_profile = UserProfiles.objects.get(user=user)
            context['profile_img'] = old_profile.img
        except UserProfiles.DoesNotExist:
            print('No User profile_img present')
        return context
    return context

Athena/templates/Athena/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta name="viewport" content=""width=device-width, initial-scale="1.0">
    <meta charset="UTF-8">
    <title>Athena</title>
    <link rel="stylesheet" type="text/css" href="{% static 'Athena/css/base_style.css' %}"/>
    <link rel="shortcut icon" type="image/png" href="{% static 'Athena/media/Athena-logo.png' %}"/>
    {% block stylesheets %} {% endblock stylesheets %}
    <!-- #ffffff light semi-light #c9d9f0 Dark #070708 -->
</head>
<body>
<div class="header">
    <div class="nav-bar">
        <div class="logo-head">

            <img width="40" height="40" src="{% static "Athena/media/Athena-logo.png" %}" alt="Logo"/>
        </div>
        <ul class="nav-links">
            <li>
                {% block nav_item_home %}
                <div class="nav-border ">
                    <a href="{% url 'dash_page' %}"><img width="40" height="40" src="https://img.icons8.com/eeeeee/sf-regular/48/home.png" alt="home"/></a>
                </div>
                {% endblock nav_item_home %}
            </li>
            <li>
                {% block nav_item_course %}
                <div class="nav-border ">
                    <a href={% url 'course_page' %}><img width="40" height="40" src="https://img.icons8.com/eeeeee/fluency-systems-regular/48/user.png" alt="user"/></a>
                </div>
                {% endblock nav_item_course %}
            </li>
            <li>
                {% block nav_item_chat %}
                <div class="nav-border ">
                    <a href=""><img width="40" height="40" src="https://img.icons8.com/eeeeee/material-outlined/48/speech-bubble-with-dots.png" alt="message"/></a>
                </div>
                {% endblock nav_item_chat %}
            </li>
            <li>
                {% block nav_item_schedule %}
                <div class="nav-border ">
                    <a href=""><img width="40" height="40" src="https://img.icons8.com/eeeeee/pulsar-line/48/thursday.png" alt="calender"/></a>
                </div>
                {% endblock nav_item_schedule %}
            </li>
            <li>
                {% block nav_item_deadlines %}
                <div class="nav-border">
                    <a href=""><img width="40" height="40" src="https://img.icons8.com/eeeeee/fluency-systems-regular/48/clock--v3.png" alt="clock--v3"/></a>
                </div>
                 {% endblock nav_item_deadlines %}
            </li>
            <li>
                {% block nav_item_settings %}
                <div class="nav-border ">
                    <a href=""><img width="40" height="40" src="https://img.icons8.com/eeeeee/fluency-systems-regular/48/settings.png" alt="settings"/></a>
                </div>
                {% endblock nav_item_settings %}
            </li>
        </ul>
    </div>
    <div class="section">
        <div class="title-bar">
            <h1 class="page-title">{{ title }}</h1>
            <div class="search-box">
                <img width="30" height="30" src="https://img.icons8.com/070708/ios/50/search--v1.png" alt="search"/>
                <input class="search-f" type="text" name="search-box" placeholder="Search">
            </div>
            <div class="nav-border dark">
                <img width="48" height="48" src="https://img.icons8.com/070708/external-creatype-outline-colourcreatype/64/external-alarm-essential-ui-v2-creatype-outline-colourcreatype-2.png" alt="external-alarm-essential-ui-v2-creatype-outline-colourcreatype-2"/>
            </div>
{#            {% if user.is_authenticated %}#}
            <div class="nav-border">
                {% if profile_img %}
                    <img id="user_profile_btn" class="rounded" width="60" height="60" src="{{ profile_img.url }}" alt="user"/>
                {% else %}
                    <img id="user_profile_btn" class="rounded" width="60" height="60" src="{% static "Athena/media/user.jpg" %}" alt="user"/>
                {% endif %}
            </div>
            <div class="menu" id="menu">
                <ul>
                    <li><a href=""><img width="20" height="20" src="https://img.icons8.com/070708/fluency-systems-regular/48/settings.png" alt="settings"/> Settings</a></li>
                    <li><a href=""><img width="20" height="20" src="https://img.icons8.com/070708/ios/50/logout-rounded--v1.png" alt="exit--v1"/>Logout</a></li>
                </ul>
            </div>
{#            {% else %}#}
            <div class="nav-border">
                <img id="user_profile_btn" class="rounded unk" width="60" height="60" src="https://img.icons8.com/222222/fluency-systems-regular/48/user.png" alt="user"/>
            </div>
            <div class="menu" id="menu">
                <ul>
                    <li><a href=""><img width="20" height="20" src="https://img.icons8.com/070708/ios/50/login-rounded-right--v1.png" alt="exit--v1"/>Login</a></li>
                </ul>
            </div>
{#            {% endif %}#}
        </div>
        <div class="page-container">
            {% block page %}

            {% endblock %}
        </div>
        <div>
        </div>
    </div>
</div>
<script src="{% static 'Athena/js/nav_bar.js' %}"></script>
{% block extrascripts %}

{% endblock %}
</body>
</html>

Athena/templates/Athena/course_details_page.html
{% extends 'Athena/base.html' %}
{% load static %}
{% load humanize %}
{% block stylesheets %}
            <link rel="stylesheet" type="text/css" href="{% static 'Athena/css/course_detials_style.css' %}"/>
{% endblock %}
{% block page %}
    <div class="info-container">
        <img class="course-banner" src="{{ course.course_banner.url }}" alt="course_banner">
        <div class="course-content">
            <h2 class="course-title">{{ course.course_title }}</h2>
            <p class="course-desc">{{ course.course_desc }}</p>
            <div class="rating-widget">
                  <div class="star-container">
                    <div class="star" data-rating="100"></div>
                    <div class="star" data-rating="100"></div>
                    <div class="star" data-rating="80"></div>
                    <div class="star" data-rating="0"></div>
                    <div class="star" data-rating="0"></div>
                  </div>
            </div>
            <div class="content-footer">
                <div class="author-card">
                    <img class="author-profile-image" src="{{ author_profile.url }}" alt="author_profile">
                    <p class="course-author"> {{ course.author.first_name }} {{ course.author.last_name }}</p>
                </div>
                {% if not e_obj %}
                    <form method="post" action="{% url 'course_enrollment' %}">
                        {% csrf_token %}
                        {{ e_form.course }}
                        {{ e_form.user }}
                        <button class="enroll-button">Enroll Now</button>
                    </form>
                {% else %}
                    <button class="enroll-button" onclick="location.href='{% url 'course_content' course.id %}'">Start Now</button>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="tabbed-view">
        <div class="tab-container">
            <button class="tab" onclick="openTab(event, 'tab1')">Content Details</button>
            <button class="tab" onclick="openTab(event, 'tab2')">Class Details</button>
            <button class="tab" onclick="openTab(event, 'tab3')">Schedule</button>
            <button class="tab" onclick="openTab(event, 'tab4')">Related Courses</button>
        </div>
        <div id="tab1" class="tab-content">
            <div class="course-content-dates">
                <div>
                    <h3>Course Created on: </h3>
                    <p>{{ course.course_created }}</p>
                </div>
                <div>
                    <h3>Course Difficulty Level: </h3>
                    <p>{{ course.get_course_difficulty_display }}</p>
                </div>
                <p class="secondary-info"> Last updated on {{ course.last_update }}
            </div>
            <h3 class="cat-title">Content Covered</h3>
            <div id="cat-container"></div>
        </div>
        <div id="tab2" class="tab-content">
             <div class="course-content-dates">
                <div>
                    <h3>Course Medium: </h3>
                    <p>{{ course.get_course_type_display }}</p>
                </div>
                <div>
                    <h3>Instructor: </h3>
                    <div class="author-card">
                        <img class="author-profile-image" src="{{ author_profile.url }}" alt="author_profile">
                        <p class="course-author"> {{ course.author.first_name }} {{ course.author.last_name }}</p>
                    </div>
                </div>
                <p class="secondary-info"> Weekly: {{ course.course_day }}
            </div>
            <h3 class="cat-title">Class Enrollments: </h3>
            <p>{{ e_info|length }} Student{{ e_info|pluralize }}</p>
{#            {% if e_info|length < 2 %}#}
{#                <p>{{ e_info|length }} Student</p>#}
{#            {% else %}#}
{#                <p>{{ e_info|length }} Students</p>#}
{#            {% endif %}#}
        </div>
        <div id="tab3" class="tab-content">
             <div class="course-content-dates">
                <div>
                    <h3>Course Starts: </h3>
                    <p>{{ course.course_start_date }}</p>
                </div>
                <div>
                    <h3>Course Ends:</h3>
                    <p>{{ course.course_end_date }}</p>
                </div>
                <p class="secondary-info"> Duration: {{ course.course_start_date|timesince:course.course_end_date }}
            </div>
            <h3 class="cat-title">Class Weekly Schedule: </h3>
            <p>{{ course.course_day }}</p>
        </div>
        <div id="tab4" class="tab-content">No related courses found</div>
    </div>

{% endblock %}
{% block extrascripts %}
    <script>
        const course_rating = '{{ course.course_rating }}';
        const course_categories = '{{ course.categories }}';
    </script>
    <script src="{% static 'Athena/js/course_details_page.js' %}"></script>
{% endblock %}

Athena/templates/Athena/course_page.html
{% extends 'Athena/base.html' %}
{% load static %}
{% block stylesheets %}
        <link rel="stylesheet" type="text/css" href="{% static 'Athena/css/cource_style.css' %}"/>
{% endblock stylesheets %}
{% block nav_item_course %}
    <div class="nav-border sel">
        <a href="/course"><img width="40" height="40" src="https://img.icons8.com/070708/fluency-systems-regular/48/user.png" alt="user"/></a>
    </div>
{% endblock nav_item_course %}
{% block page %}
    <!-- Auto course animation on the top -->
    <div class="banner-widget">

        <div class="banner-container" id="banner-container">
          <div class="banner-image">
            <img id="course-image" src="" alt="Course Image">
          </div>
          <div id="course-image-overlay" class="banner_overlay"></div>

          <div class="banner-content">
            <h2 id="course-title"></h2>
            <p id="course-description"></p>
            <p id="course-author"></p>
          </div>
        </div>
        <div class="banner-navigation">
            <span></span>
            <button id="prev-button">
                <img width="36" height="36" class="rotate" src="https://img.icons8.com/pastel-glyph/64/circled-chevron-right.png" alt="circled-chevron-right--v1"/>
            </button>
            <div id="circle-container"></div>
            <button id="next-button">
                <img width="36" height="36" src="https://img.icons8.com/pastel-glyph/64/circled-chevron-right.png" alt="circled-chevron-right--v1"/>
            </button>
            <span></span>
        </div>
    </div>
    <!-- Add condition that only If the user is Lesser or above only show this -->
    <div class="title_1_container">
        <h2 class="title_h2">My Courses</h2>
        <button class="primary-btn" onclick="location.href=''">
            Create
        </button>
    </div>

    <div class="course_box">
        {% for course in my_courses %}
        <div class="course-view">
            <div class="course-card">
                <a href="">
                    <img class="course_logo" src="{{ course.course_banner.url }}" alt="Course Logo">
                </a>
            </div>
            <h3>{{ course.course_title }}</h3>
            <p>By: {{ course.author.first_name }} {{ course.author.last_name }}</p>
        </div>
        {% empty %}
            <div class="center-box">
                <p>No courses created yet. Click on the create button to build new course.</p>
            </div>
        {% endfor %}
    </div>
    {% if e_courses|length > 0 %}
        <div class="title_1_container">
            <h2 class="title_h2">Enrolled Courses</h2>
            {% if e_courses|length > 3 %}
                <button class="secondary-btn">
                    View All
                </button>
            {% endif %}
        </div>
        <div class="course_box">
            {% for enroll in e_courses %}
            <div class="course-view">
                <div class="course-card">
                    <a href="{% url 'course_details_page' enroll.course.id %}">
                        <img class="course_logo" src="{{ enroll.course.course_banner.url }}" alt="Course Logo">
                    </a>
                </div>
                <h3>{{ enroll.course.course_title }}</h3>
                <p>By: {{ enroll.course.author.first_name }} {{ enroll.course.author.last_name }}</p>
            </div>
            {% empty %}
                <div class="center-box">
                    <p>Not enrolled into any courses yet.</p>
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <!-- Normal Courses visible to all -->
    <div class="title_1_container">
        <h2 class="title_h2">All Courses</h2>
        <button class="secondary-btn" onclick="location.href=''">
            View All
        </button>
    </div>
    <div id="course-container" class="course-container">
        {% for course in v_courses %}
            <div class="course-view t-b-margin">
              <div class="course-card">
                <a href="">
                  <img class="course_logo" src="{{ course.course_banner.url }}" alt="Course Logo">
                </a>
              </div>
              <h3>{{ course.course_title }}</h3>
              <p>By: {{ course.author.first_name }} {{ course.author.last_name }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block extrascripts %}
    <script>
        var courses = [];
        var course_link = '';
        {% for course in t_courses %}
            cos = {}
            cos['course_id'] = "{{ course.id|escapejs }}";
            cos['course_banner'] = "{{ course.course_banner.url|escapejs }}";
            cos['course_title'] = "{{ course.course_title|escapejs }}";
            cos['course_desc'] = "{{ course.course_desc|escapejs }}";
            cos['course_author'] = "{{ course.author.first_name|escapejs }} {{ course.author.last_name|escapejs }}";
            courses.push(cos);
        {% endfor %}
    </script>
    <script src="{% static 'Athena/js/course_page.js' %}"></script>
{% endblock %}

Athena/templates/Athena/dash_page.html
{% extends 'Athena/base.html' %}
{% block nav_item_home %}
    <div class="nav-border sel">
        <a href="/dash"><img width="40" height="40" src="https://img.icons8.com/070708/sf-regular/48/home.png" alt="home"/></a>
    </div>
{% endblock nav_item_home %}
{% block page %}
    <p> Dash Pages</p>
{% endblock %}

Athena/templates/Athena/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <title>Athena Login</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Anton&family=Pacifico&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'Athena/css/login_style.css' %}"/>
        <link rel="shortcut icon" type="image/png" href="{% static 'Athena/media/Athena-logo.png' %}"/>
    </head>
    <body style="background-image: url('{% static "Athena/media/login-bg.svg" %}'); background-size: cover;">
        <div class="login-container">
            <div class="brand">
                <img src="{% static 'Athena/media/athena-50.png' %}" alt="User Icon" width="50" height="50">
                <h1>Athena</h1>
            </div>
            <div class="login-card">
                <form action="/login" method="post">
                    {% csrf_token %}
                  <label>
                    <img src="{% static 'Athena/media/email.png' %}" alt="User Icon" width="20" height="20">
                    <input type="email" name="email" placeholder="Email Address" required>
                  </label>
                  <label>
                    <img src="{% static 'Athena/media/password.png' %}" alt="Password Icon" width="24" height="24">
                    <input type="password" name="password" placeholder="Password" required>
                  </label>
                  <div class="center-btn">
                    <input type="submit" value="Log in" class="submit-button">
                  </div>
                </form>
            </div>
            <a href="#">Forgot password?</a>
        </div>
    </body>
</html>